# Generated by Django 5.2.5 on 2025-08-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['sequence'], 'verbose_name': 'Карта Таро', 'verbose_name_plural': 'Карты Таро'},
        ),
        migrations.RemoveField(
            model_name='card',
            name='description',
        ),
        migrations.AddField(
            model_name='card',
            name='cardtype',
            field=models.CharField(choices=[('major', 'Старший аркан'), ('minor', 'Младший аркан')], default='major', max_length=10, verbose_name='Тип карты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='desc',
            field=models.TextField(default='dfsd', verbose_name='Описание прямого значения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='hebrew_letter',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Буква иврита'),
        ),
        migrations.AddField(
            model_name='card',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое послание'),
        ),
        migrations.AddField(
            model_name='card',
            name='qabalah',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Каббала'),
        ),
        migrations.AddField(
            model_name='card',
            name='rdesc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание перевёрнутого значения'),
        ),
        migrations.AddField(
            model_name='card',
            name='sequence',
            field=models.PositiveIntegerField(default=666, verbose_name='Номер карты в колоде'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='suit',
            field=models.CharField(blank=True, choices=[('wands', 'Жезлы'), ('cups', 'Кубки'), ('swords', 'Мечи'), ('pentacles', 'Пентакли')], max_length=10, null=True, verbose_name='Масть'),
        ),
        migrations.AddField(
            model_name='card',
            name='url',
            field=models.SlugField(default='ghdf', unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='cards/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название карты'),
        ),
    ]
