# Generated by Django 5.2.5 on 2025-08-13 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userrequesthistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequesthistory',
            old_name='query',
            new_name='request_text',
        ),
        migrations.AlterField(
            model_name='userrequesthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.user'),
        ),
    ]
