# Generated by Django 5.2.5 on 2025-08-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_query_userrequesthistory_request_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrequesthistory',
            options={'verbose_name': 'User request history', 'verbose_name_plural': 'User request histories'},
        ),
    ]
